#!/bin/sh
export POSIXLY_CORRECT=yes
export LC_NUMERIC=en.US.UTF-8
help_print()
{
    echo ""
    echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
    echo "-h|--help   vypsani napovedy"
    echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
    echo "[FILTR]"

    echo "[PŘÍKAZ]"

}
PRIKAZ=""
FILES=""
GZ_FILES="" 
while [ "$#" -gt 0 ] 
do
    case "$1" in
        -h|--help)
            help_print
            exit 0
            ;;
        list-tick)
            PRIKAZ="list-tick"
            shift
            ;;
        -w)
            WIDTH="$2"
            shift
            shift
            ;;
        *)
            case "$1" in 
                *.gz*)
                    echo GZ
                    GZ_FILES=" $1 $GZ_FILES"
                     ;;
                *)
                echo "normal file"
                FILES="$1 $FILES"
            esac    
            shift
            ;;
    esac
done
if [ "$FILES" = "" ]; then  #pokud je neni zadany soubor cti z toho co ti zada
    while read line
    do
    echo "$line"
    done < "${1:-/dev/stdin}"   
    exit 1
else
    value=$(cat $FILES)
    echo "$value"
fi



echo "$PRIKAZ"
echo "$FILES"
echo "$GZ_FILES"

