#!/bin/sh
#####################################################
################### Projekt č.1 #####################
###################  Tradelog #######################
################## Petr Hýbl ########################
##################  4.4.2021 ########################
export POSIXLY_CORRECT=yes
export LC_NUMERIC=en.US.UTF-8
help_print()
{
    echo ""
    echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
    echo "-h|--help   vypsani napovedy"
    echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
    echo "[FILTR]"
    echo "-a DATETIME    zaznamy po tomto datu format YYYY-MM-DD HH:MM:SS"
    echo "-b DATETIME    zaznamy pred timto datem format YYYY-MM-DD HH:MM:SS"
    echo "-t TICKER      pouze zaznamy s promennou TICKER, lze zadat vice"
    echo "-w WIDTH       nastavuje sirku WIDTH pro prikazy graph-pos a hist-ord, musi byt kladne cele cislo"
    echo "[PŘÍKAZ]"
    echo "list-tick      vypis vsech tickeru v zaznamu"
    echo "profit         vypis celkoveho zisku uzavrenych pozic"
    echo "pos            vypis hodnot aktualne drzenych pozic "
    echo "last-price     vypis posledni zname ceny pro kazdy ticker"
    echo "hist-ord       vypis histogramu poctu transakci dle tickeru"
    echo "graph-pos      vypis grafu hodnot drzenych pozic dle tickeru"
    echo "[LOG [LOG2 [...]]"
    echo "soubory ze kterych se budou cist logy transakci"

}


FILTR=""
POCETTICKERU=0
AFTERDATE="1000-01-01 01:01:01"
BEFOREDATE="9999-12-31 23:59:59"
PRIKAZ=""
FILES=""
GZ_FILES="" 
WIDTH="0"
NULA="0"
WIDTHCOUNTER="0"
while [ "$#" -gt 0 ]  ## kontrola parametru a zapamatovani si jich do promennych
do
    case "$1" in
        -h|--help)
            help_print
            exit 0
            ;;
        list-tick)
            PRIKAZ="list-tick"
            shift
            ;;
        -w)
            
            if [ "$NULA" -gt "$2" ]
            then
            echo CHYBA
            exit 1
            fi
            if [ "$WIDTHCOUNTER" = "1" ]
            then
            echo CHYBA
            exit 1
            fi
            WIDTH="$2"
            WIDTHCOUNTER=$(echo "$WIDTHCOUNTER+1" | bc)
            shift
            shift
            ;;
        profit)
            PRIKAZ="profit"
            shift
            ;;
        
        -t)
            FILTR="$2 $FILTR"
            POCETTICKERU=$(echo "$POCETTICKERU+1" | bc)
            shift
            shift
            ;;
        pos)
            PRIKAZ="pos"
            shift
            ;;
        last-price)
            PRIKAZ="last-price"
            shift
            ;;
        -a)
            AFTERDATE="$2"
            shift
            shift
            ;;
        -b)
            BEFOREDATE="$2"
            shift
            shift
            ;;
        hist-ord)
            PRIKAZ="hist-ord"
            shift
            ;;
        graph-pos)
            PRIKAZ="graph-pos"
            shift
            ;;         
        *)
            case "$1" in 
                *.gz*)
                    GZ_FILES="$GZ_FILES $1"
                     ;;
                *) 
                    FILES="$FILES $1" #pridat vic files
            esac    
            shift
            ;;
    esac
done
if  [ "$PRIKAZ" = "graph-pos" ] &&  [ "$WIDTH" = "0" ]
then
    WIDTH="default" # pokud nebude parametr nastavice specialni
fi

if [ "$FILES" = "" ] && [ "$GZ_FILES" = "" ]; then  #pokud je neni zadany soubor cti z toho co ti zada
    while read -r line
    do
    NACTENYTEXT=$(echo "$NACTENYTEXT" | awk -F ';' -v line="$line" ' 
    {
            if($0!="")
            print $0
            }
            END {
                    print line
    }' ##nacitani ze stdiin
)
    done 
else
  if [ "$GZ_FILES" != "" ]; then
        if [ "$FILES" != "" ]; then
                FILTRTEXT=$(eval gzip -q -d -c "$GZ_FILES")
                FILTRTEXT="$FILTRTEXT $(cat "$FILES")"
            else
                FILTRTEXT=$(eval gzip -q -d -c "$GZ_FILES")
        fi
  elif [ "$FILES" != "" ]; then
        FILTRTEXT=$(eval cat "$FILES")
  else
        exit 1
  fi   #nactenitextu i z zipu
fi   
 

echo "$FILTRTEXT"
                                                            
if [ "$POCETTICKERU" != "0" ]  #FILTRACE TICKERU
then
FILTRTEXT=$(echo "$NACTENYTEXT" | awk -F ';' -v ticker="$FILTR" -v pocettickeru="$POCETTICKERU" '
{
    split(ticker,b," ")
    i = 1
    while (i <= pocettickeru) { 
        if($2==b[i]){print $0}
        i++
    } 
}' #postupne nacitani radku pouze s tickerem ktery potrebujeme
) 
else
    FILTRTEXT="$NACTENYTEXT"   #pokud neni zadany prekopirujeme cely seznam
fi

if [ "$AFTERDATE" != "1000-01-01 01:01:01" ] 
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' -v afterdate="$AFTERDATE" '
{
    if($1>afterdate){print $0}  

}' #filtrace datumu
)
fi
if [ "$BEFOREDATE" != "9999-12-31 23:59:59" ]
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' -v beforedate="$BEFOREDATE" '
{
    if($1<beforedate){print $0}  
}'
) #filtrace datumu
fi
if [ "$PRIKAZ" = "" ]  # pokud neni zadany prikaz zobraz cely text
then
echo "$FILTRTEXT"
fi

# LIST TICK VYPIS
TICKERS="" 
if [ "$PRIKAZ" = "list-tick" ] 
then
TICKERS=$(echo "$FILTRTEXT" | awk -F ';' '
{
    {print $2}  
}'
)  
    echo "$TICKERS" | sort -u  # vypisovani pouze TICKERU, sort- abecedne
fi

# PROFIT VYPIS
SUMABUY=0
SUMASELL=0
if [ "$PRIKAZ" = "profit" ] 
then
if  [ "$FILTRTEXT" = "" ] #pokud neni text rovnou vypis nulu
then
    echo "0.00"

else
   SUMASELL=$(echo "$FILTRTEXT" | awk -F ';' '
{
    hodnota=0
    if($3=="sell"){
        hodnota=$4*$6
        printf "%.2f ", hodnota
    }
    
}'
)
# pocitame postupne hodnoty sell
SUMASELL=$(echo "$SUMASELL" | tr ' ' + ) #nahrazeni pluska místo mezery
SUMASELL=$(echo "$SUMASELL" | sed 's/.$//') # odebrani posledniho +
SUMASELL=$(echo "$SUMASELL" | bc ) #vypocitani vyrazu
SUMABUY=$(echo "$FILTRTEXT" | awk -F ';' -v hodnota=0 '
{
    hodnota=0
    if($3=="buy"){
        hodnota=$4*$6
        printf "%.2f ", hodnota
    }
    
}'
) # pocitame postupne hodnoty sell
SUMABUY=$(echo "$SUMABUY" | tr ' ' + ) #nahrazeni pluska místo mezery
SUMABUY=$(echo "$SUMABUY" | sed 's/.$//') # odebrani posledniho +
SUMABUY=$(echo "$SUMABUY" | bc ) #vypocitani vyrazu
echo "$SUMASELL-$SUMABUY" | bc #spocitani celkoveho profitu
fi
fi  



# POSITION VYPIS

if [ "$PRIKAZ" = "pos" ] 
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
   if($3=="buy")   
   {
       objem[$2]+=$6 
       }  
    if($3=="sell")   
   {
       objem[$2]-=$6 
       }
    poslednihodnota[$2]=$4
    }
    
    END {
    for(ticker in objem)
    {
        value=objem[ticker]*poslednihodnota[ticker]
        printf("%.2f %s\n", value,ticker)
    }
}'
) #vypocitani aktualni pozice pro kazdy ticker
FILTRTEXT=$(echo "$FILTRTEXT" | sort -n -r) #serazeni podle cisel
NEJDELSICISLO=$(echo "$FILTRTEXT" | awk -F ' ' '
{
    cislo=$1
    if(length(cislo)>nejdelsicislo)
    {
        nejdelsicislo=length(cislo)
    }
    }
    END{
        print nejdelsicislo

}'
) #vypocitani nejdelsiho cisla
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nejdelsicislo="$NEJDELSICISLO" '
{
    printf("%10-s: %*.2f\n", $2,nejdelsicislo,$1)
}'
) #vypsani cisel se zarovnanim

echo "$FILTRTEXT"
fi
##LAST PRICE VYPIS
if [ "$PRIKAZ" = "last-price" ] 
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
    
    poslednihodnota[$2]=$4
    }
    END {
    for(ticker in poslednihodnota)
    {
        printf("%s %.2f\n",ticker, poslednihodnota[ticker])
    }
}'
) #vypsani posledni hodnoty pro kazdy ticker
FILTRTEXT=$(echo "$FILTRTEXT" | sort) #serazeni abecedne

NEJDELSICISLO=$( echo "$FILTRTEXT" | awk -F ' ' '
{
    cislo=$2
    if(length(cislo)>nejdelsicislo)
    {
        nejdelsicislo=length(cislo)
    }
    }
    END{
        print nejdelsicislo

}'
) #vypocitani nejdelsiho cisla
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nejdelsicislo="$NEJDELSICISLO" '
{
    printf("%10-s: %*.2f\n", $1,nejdelsicislo,$2)
}'
) # zarovnany vypis
echo "$FILTRTEXT"
fi

# HIST-ORD 
if [ "$PRIKAZ" = "hist-ord" ] 
then
if [ "$WIDTH" = "0" ] 
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
    pocetransakci[$2]=pocetransakci[$2]+1
    }
    END {
    for(ticker in pocetransakci)
    {
        printf("%s ",ticker, pocetransakci[ticker])
        for (i = 0; i < pocetransakci[ticker]; i++)
        printf("#")
        printf("\n")
    }
}'
) # scitani poctu transakci pote za kazdou transakci napise hastag
FILTRTEXT=$(echo "$FILTRTEXT" | sort)
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' '
{
    printf("%10-s: %s\n", $1,$2)
}'
) # zarovnani
echo "$FILTRTEXT"    
else
    FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
    pocetransakci[$2]=pocetransakci[$2]+1
    }
    END {
    for(ticker in pocetransakci)
    {
        printf("%s %d \n",ticker, pocetransakci[ticker])

    }
}'
) #vypocitani poctu transakci pro kazdy ticker

NEJVETSITRANSAKCE=$(echo "$FILTRTEXT" | awk -F ' ' -v number=0 '
{
    if(number<$2)
    {
        number=$2
    }
    }
    END {
    print number 
    }'
)
# spocitani nejvetsiho cisla
NASOBIC=$WIDTH/$NEJVETSITRANSAKCE
NASOBIC=$(echo "$NASOBIC" | bc -l ) # prepocitani jakou hodnotu bude mít jeden hashtag

FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nasobic=$NASOBIC '
{
    
    pocettransakci=nasobic*$2
    printf("%10-s: ",$1)
    for (i = 1; i <= pocettransakci; i++)
    printf("#")
    printf("\n")
}'
) #pocettransakci vynasobim nasobicem hodnot abych zjistil celkovy pocet hastagu
FILTRTEXT=$(echo "$FILTRTEXT" | sort)
echo "$FILTRTEXT"
fi
fi

#GRAF-POS
if [ "$PRIKAZ" = "graph-pos" ] 
then

FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
   if($3=="buy")   
   {
       objem[$2]+=$6 
       }  
    if($3=="sell")   
   {
       objem[$2]-=$6 
       }
    poslednihodnota[$2]=$4
    }
    
    END {
    for(ticker in objem)
    {
        value=objem[ticker]*poslednihodnota[ticker]
        printf("%s %.2f \n", ticker, value)
    }
}'
)
#vypocitani profitu
FILTRTEXT=$(echo "$FILTRTEXT" | sort) #serazeni
if [ "$WIDTH" != "default" ]
then
NEJVETSICISLO=$(echo "$FILTRTEXT" | awk -F ' ' -v number=0 '
{
    hodnota=$2
    if($2<0)
    {
        hodnota=$2*(-1)

    }
    if(nejnumber<hodnota)
    {
        nejnumber=hodnota
    }
    }
    END {
    printf("%f",nejnumber)  
    }'
)
#hledani absolutni hodnoty nejvetsiho cisla 
NASOBIC=$NEJVETSICISLO/$WIDTH
NASOBIC=$(echo "$NASOBIC" | bc -l )
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nasobic="$NASOBIC" '
{
   if($2>0)
   {
       znak="#"
       hodnota=$2
   }
   if($2<0)
   {
       znak="!"
       hodnota=$2*(-1)
   }
    printf("%10-s:",$1)
    for (i = nasobic; i <= hodnota; i=i+nasobic)
    {
        if(i==nasobic)
        {
            printf(" ")
        }
        printf("%s",znak)

    }

    printf("\n")

}'
) #vypis ! nebo # pro velikost cisla profitu
echo "$FILTRTEXT"
else
#bez width je nasobic 1000 jedna hodnota znaku = 1000
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nasobic=1000 '
{
       if($2>0)
   {
       znak="#"
       hodnota=$2
   }
   if($2<0)
   {
       znak="!"
       hodnota=$2*(-1)
   }
    printf("%10-s:",$1)
    for (i = nasobic; i <= hodnota; i=i+nasobic)
    {
        if(i==nasobic)
        {
            printf(" ")
        }
        printf("%s",znak)

    }
    printf("\n")
}'
)
echo "$FILTRTEXT"
fi
fi

