#!/bin/sh
export POSIXLY_CORRECT=yes
export LC_NUMERIC=en.US.UTF-8
help_print()
{
    echo ""
    echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
    echo "-h|--help   vypsani napovedy"
    echo "tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
    echo "[FILTR]"

    echo "[PŘÍKAZ]"

}
#TODO HELP CELY
#TODO HLAVICKU SOUBORU
FILTR=""
POCETTICKERU=0
AFTERDATE="1000-01-01 01:01:01"
BEFOREDATE="9999-12-31 23:59:59"
PRIKAZ=""
FILES=""
GZ_FILES="" 
while [ "$#" -gt 0 ] 
do
    case "$1" in
        -h|--help)
            help_print
            exit 0
            ;;
        list-tick)
            PRIKAZ="list-tick"
            shift
            ;;
        -w)
            WIDTH="$2"
            shift
            shift
            ;;
        profit)
            PRIKAZ="profit"
            shift
            ;;
        
        -t)
            FILTR="$2 $FILTR"
            POCETTICKERU=$(echo "$POCETTICKERU+1" | bc)
            shift
            shift
            ;;
        pos)
            PRIKAZ="pos"
            shift
            ;;
        last-price)
            PRIKAZ="last-price"
            shift
            ;;
        -a)
            AFTERDATE="$2 $3"
            shift
            shift
            shift
            ;;
        -b)
            BEFOREDATE="$2 $3"
            shift
            shift
            shift
            ;;
        *)
            case "$1" in 
                *.gz*)
                    GZ_FILES="$1 $GZ_FILES"
                     ;;
                *) 
                    FILES="$1 $FILES" #pridat vic files
            esac    
            shift
            ;;
    esac
done

NACTENYTEXT=$(gzip -q -d -c $GZ_FILES | cat $FILES -) #nactenitextu i z zipu
if [ "$POCETTICKERU" != "0" ] 
then
FILTRTEXT=$(echo "$NACTENYTEXT" | awk -F ';' -v ticker="$FILTR" -v pocettickeru="$POCETTICKERU" '
{
    split(ticker,b," ")
    i = 1
    while (i <= pocettickeru) {
        if($2==b[i]){print $0}
        i++
    } 
}'
) 
else
    FILTRTEXT="$NACTENYTEXT"   
fi
# echo $AFTERDATE
if [ "$AFTERDATE" != "1000-01-01 01:01:01" ]
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' -v afterdate="$AFTERDATE" '
{
    if($1>afterdate){print $0}  
}'
)
fi
# echo $BEFOREDATE
if [ "$BEFOREDATE" != "9999-12-31 23:59:59" ]
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' -v beforedate="$BEFOREDATE" '
{
    if($1<beforedate){print $0}  
}'
)
fi
if [ "$PRIKAZ" = "" ] 
then
echo "$FILTRTEXT"
fi

#LIST TICK VYPIS
TICKERS="" 
if [ "$PRIKAZ" = "list-tick" ] 
then
TICKERS=$(echo "$FILTRTEXT" | awk -F ';' '
{
    {print $2}  
}'
)  
    echo "$TICKERS" | sort -u 
fi

#PROFIT VYPIS
SUMABUY=0
SUMASELL=0
if [ "$PRIKAZ" = "profit" ] 
then
   SUMASELL=$(echo "$FILTRTEXT" | awk -F ';' '
{
    hodnota=0
    if($3=="sell"){
        hodnota=$4*$6
        printf "%.2f ", hodnota
    }
    
}'
)
SUMASELL=$(echo "$SUMASELL" | tr ' ' + )
SUMASELL=$(echo "$SUMASELL" | sed 's/.$//')
SUMASELL=$(echo "$SUMASELL" | bc )
SUMABUY=$(echo "$FILTRTEXT" | awk -F ';' -v hodnota=0 '
{
    hodnota=0
    if($3=="buy"){
        hodnota=$4*$6
        printf "%.2f ", hodnota
    }
    
}'
)
SUMABUY=$(echo "$SUMABUY" | tr ' ' + )
SUMABUY=$(echo "$SUMABUY" | sed 's/.$//')
SUMABUY=$(echo "$SUMABUY" | bc )
echo "$SUMASELL-$SUMABUY" | bc
fi  



# #POSITION VYPIS

if [ "$PRIKAZ" = "pos" ] 
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
   if($3=="buy")   
   {
       objem[$2]+=$6 
       }  
    if($3=="sell")   
   {
       objem[$2]-=$6 
       }
    poslednihodnota[$2]=$4
    }
    
    END {
    for(ticker in objem)
    {
        value=objem[ticker]*poslednihodnota[ticker]
        printf("%.2f %s\n", value,ticker)
    }
}'
)
FILTRTEXT=$(echo "$FILTRTEXT" | sort -n -r)
NEJDELSICISLO=$( echo "$FILTRTEXT" | awk -F ' ' '
{
    cislo=$1
    if(length(cislo)>nejdelsicislo)
    {
        nejdelsicislo=length(cislo)
    }
    }
    END{
        print nejdelsicislo

}'
)
echo "$NEJDELSICISLO"
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nejdelsicislo="$NEJDELSICISLO" '
{
    printf("%10-s: %*.2f\n", $2,nejdelsicislo,$1)
}'
)

echo "$FILTRTEXT"
fi
##LAST PRICE VYPIS
if [ "$PRIKAZ" = "last-price" ] 
then
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ';' '
{
    
    poslednihodnota[$2]=$4
    }
    END {
    for(ticker in poslednihodnota)
    {
        printf("%s %.2f\n",ticker, poslednihodnota[ticker])
    }
}'
)
FILTRTEXT=$(echo "$FILTRTEXT" | sort)

NEJDELSICISLO=$( echo "$FILTRTEXT" | awk -F ' ' '
{
    cislo=$2
    if(length(cislo)>nejdelsicislo)
    {
        nejdelsicislo=length(cislo)
    }
    }
    END{
        print nejdelsicislo

}'
)
echo "$NEJDELSICISLO"
FILTRTEXT=$(echo "$FILTRTEXT" | awk -F ' ' -v nejdelsicislo="$NEJDELSICISLO" '
{
    printf("%10-s: %*.2f\n", $1,nejdelsicislo,$2)
}'
)
echo "$FILTRTEXT"
fi

echo "PRIKAZ $PRIKAZ"
echo "SOUBORY $FILES"
echo "GZ SOUBORY $GZ_FILES"
echo "FILTER $FILTR $FILTRCOUNTER"

